#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	0
bspc config window_gap		80

bspc config left_padding 	80
bspc config right_padding	80
bspc config top_padding 	0
bspc config bottom_padding	0

bspc config split_ratio		0.50
bspc config borderless_monocle	true
bspc config gapless_monocle	true

bspc config history_aware_focus	true
bspc config focus_by_distance	true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# font
# fc-cache -fv &
fc-cache -fv

# wallpaper
# paperview ~/dots/wallpaper/ 1 & # doesnt work with picom
feh --bg-scale ~/dots/wallpapers/arseniy-chebynkin-modern-metropolis-no-watermark.jpg

# picom
killall picom
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom -f -D 3 &

# polybar
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar top &
polybar bottom &

xmousepasteblock &
